# Generated by Django 5.2.6 on 2025-09-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbase',
            name='nombre',
        ),
    ]
