# Generated by Django 5.2.6 on 2025-09-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appapi', '0002_remove_pbase_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botones',
            fields=[
                ('id_botones', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('estilos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Botón',
                'verbose_name_plural': 'Botones',
                'db_table': 'botones',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('estilo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Iconos',
            fields=[
                ('id_iconos', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Icono',
                'verbose_name_plural': 'Iconos',
                'db_table': 'iconos',
            },
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('estilos', models.IntegerField(blank=True, null=True)),
                ('id_iconos', models.ForeignKey(blank=True, db_column='id-iconos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appapi.iconos')),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
                'db_table': 'inputs',
            },
        ),
        migrations.CreateModel(
            name='Variados',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('estilos', models.TextField(blank=True, null=True)),
                ('id_iconos', models.ForeignKey(blank=True, db_column='id-iconos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appapi.iconos')),
            ],
            options={
                'verbose_name': 'Variado',
                'verbose_name_plural': 'Variados',
                'db_table': 'variados',
            },
        ),
        migrations.DeleteModel(
            name='pbase',
        ),
        migrations.AddField(
            model_name='cards',
            name='id_iconos',
            field=models.ForeignKey(blank=True, db_column='id-iconos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appapi.iconos'),
        ),
        migrations.AddField(
            model_name='botones',
            name='id_iconos',
            field=models.ForeignKey(blank=True, db_column='id-iconos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appapi.iconos'),
        ),
    ]
