# Generated by Django 6.0 on 2025-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appapi', '0003_botones_cards_iconos_inputs_variados_delete_pbase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botones',
            name='codigo',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='cards',
            name='codigo',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='iconos',
            name='codigo',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='inputs',
            name='codigo',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='variados',
            name='codigo',
            field=models.CharField(max_length=4000),
        ),
    ]
