# Generated by Django 5.2.1 on 2025-12-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appapi', '0004_alter_botones_codigo_alter_cards_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botones',
            old_name='id_botones',
            new_name='id_boton',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='id',
            new_name='id_card',
        ),
        migrations.RenameField(
            model_name='iconos',
            old_name='id_iconos',
            new_name='id_icono',
        ),
        migrations.RenameField(
            model_name='variados',
            old_name='id',
            new_name='id_variado',
        ),
        migrations.RemoveField(
            model_name='botones',
            name='estilos',
        ),
        migrations.RemoveField(
            model_name='botones',
            name='id_iconos',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='estilo',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='id_iconos',
        ),
        migrations.RemoveField(
            model_name='inputs',
            name='estilos',
        ),
        migrations.RemoveField(
            model_name='inputs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inputs',
            name='id_iconos',
        ),
        migrations.RemoveField(
            model_name='variados',
            name='estilos',
        ),
        migrations.RemoveField(
            model_name='variados',
            name='id_iconos',
        ),
        migrations.AddField(
            model_name='inputs',
            name='id_input',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
